language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - composer self-update
  - composer clear-cache

install:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

